<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.7.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlataformaECommerce.Application\PlataformaECommerce.Application.csproj" />
    <ProjectReference Include="..\PlataformaECommerce.Domain\PlataformaECommerce.Domain.csproj" />
    <ProjectReference Include="..\PlataformaECommerce.Infrastructure\PlataformaECommerce.Infrastructure.csproj" />
    <ProjectReference Include="..\PlataformaECommerce.Web\PlataformaECommerce.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\Catalog\" />
    <Folder Include="Application\Auth\" />
    <Folder Include="Application\Orders\" />
    <Folder Include="Common\" />
    <Folder Include="Domain\Entities\" />
    <Folder Include="Domain\Cart\" />
    <Folder Include="Domain\Orders\" />
    <Folder Include="Domain\Users\" />
    <Folder Include="Domain\Products\" />
    <Folder Include="Infrastructure\Audit\" />
    <Folder Include="Infrastructure\Products\" />
    <Folder Include="Web\" />
  </ItemGroup>

</Project>
